<?php
/**
 * Definizione di entita' di uso comune
 *  
 * @package tag
 * @author Ubik <emiliano.leporati@gmail.com>
 */


/**
 * Il BR di XHTML
 */
define("BR","<br />");

define("NBSP", "&#160;");
define("EURO", "&#x20AC;");
define("ELLIPSIS", "&#8230;");

define('IEXCL' ,  '');
define('CENT'  ,  '');
define('POUND' ,  '');
define('CURREN',  '');
define('YEN'   ,  '');
define('BRVBAR',  '');
define('SECT'  ,  '');
define('UML'   ,  '');
define('COPY'  ,  '&#xA9;');
define('ORDF'  ,  '');
define('LAQUO' ,  '&#xAB;');
define('NOT'   ,  '');
define('SHY'   ,  '');
define('REG'   ,  '&#xAE;');
define('TRADE' ,  '&#x2122;');
define('MACR'  ,  '');
define('DEG'   ,  '&#xB0;');
define('PLUSMN',  '');
define('SUP2'  ,  '');
define('SUP3'  ,  '');
define('ACUTE' ,  '');
define('MICRO' ,  '');
define('PARA'  ,  '');
define('MIDDOT',  '');
define('CEDIL' ,  '');
define('SUP1'  ,  '');
define('ORDM'  ,  '');
define('RAQUO' ,  '&#xBB;');
define('FRAC14',  '');
define('FRAC12',  '');
define('FRAC34',  '');
define('IQUEST',  '');
define('AGRAVE',  '&AGRAVE;');
define('AACUTE',  '&AACUTE');
define('ACIRC' ,  '&ACIRC;');
define('ATILDE',  '&ATILDE;');
define('AUML'  ,  '&AMUL;');
define('ARING' ,  '');
define('AELIG' ,  '');
define('CCEDIL',  '');
define('EGRAVE',  '');
define('EACUTE',  '');
define('ECIRC' ,  '');
define('EUML'  ,  '');
define('IGRAVE',  '');
define('IACUTE',  '');
define('ICIRC' ,  '');
define('IUML'  ,  '');
define('ETH'   ,  '');
define('NTILDE',  '');
define('OGRAVE',  '');
define('OACUTE',  '');
define('OCIRC' ,  '');
define('OTILDE',  '');
define('OUML'  ,  '');
define('TIMES' ,  '');
define('OSLASH',  '');
define('UGRAVE',  '');
define('UACUTE',  '');
define('UCIRC' ,  '');
define('UUML'  ,  '');
define('YACUTE',  '');
define('THORN' ,  '');
define('SZLIG' ,  '');
define('agrave',  '&agrave;');
define('aacute',  '&aacute;');
define('acirc' ,  '&acirc;');
define('atilde',  '&atilde;');
define('auml'  ,  '&amul;');
define('aring' ,  '&aring;');
define('aelig' ,  '');
define('ccedil',  '');
define('egrave',  '&egrave;');
define('eacute',  '&eacute;');
define('ecirc' ,  '&ecirc;');
define('euml'  ,  '');
define('igrave',  '');
define('iacute',  '');
define('icirc' ,  '');
define('iuml'  ,  '');
define('eth'   ,  '');
define('ntilde',  '');
define('ograve',  '');
define('oacute',  '');
define('ocirc' ,  '');
define('otilde',  '');
define('ouml'  ,  '');
define('DIVIDE',  '');
define('oslash',  '');
define('ugrave',  '');
define('uacute',  '');
define('ucirc' ,  '');
define('uuml'  ,  '');
define('yacute',  '');
define('thorn' ,  '');
define('YUML'  ,  '');
define('QUOT'  ,  '"');
define('LT'    ,  '<');
define('GT'    ,  '>');
define('AMP'   ,  '&');

?>